using System;
using System.Collections.Generic;
using System.IO;
using System.Numerics;
using System.Threading.Tasks;
using Dalamud.Bindings.ImGui;
using Dalamud.Interface.ImGuiFileDialog;
using Dalamud.Interface.Utility.Raii;
using Dalamud.Interface.Windowing;
using SkinTattoo.Core;
using SkinTattoo.Services;
using SkinTattoo.Services.Localization;

namespace SkinTattoo.Gui;

public class ModExportWindow : Window
{
    private readonly DecalProject project;
    private readonly ModExportService exportService;
    private readonly Configuration config;
    private readonly FileDialogManager fileDialog = new();

    private ExportTarget currentTarget = ExportTarget.LocalPmp;
    private string modName = "";
    private string author = "";
    private string version = "1.0";
    private string description = "";
    private string outputPath = "";
    private readonly HashSet<int> selectedGroupIndices = new();

    // Written from background Task.Run, read from UI thread  -- volatile so UI sees the unset
    private volatile bool exporting;

    public ModExportWindow(DecalProject project, ModExportService exportService, Configuration config)
        : base(Strings.T("window.export.title") + "###SkinTattooExport",
               ImGuiWindowFlags.NoCollapse)
    {
        this.project = project;
        this.exportService = exportService;
        this.config = config;

        SizeConstraints = new WindowSizeConstraints
        {
            MinimumSize = new Vector2(440, 400),
            MaximumSize = new Vector2(640, 800),
        };
        IsOpen = false;
    }

    /// <summary>Open the dialog with a target preset. Resets fields from config defaults.</summary>
    public void OpenAs(ExportTarget target)
    {
        currentTarget = target;
        WindowName = target == ExportTarget.LocalPmp
            ? Strings.T("window.export.title_local") + "###SkinTattooExport"
            : Strings.T("window.export.title_penumbra") + "###SkinTattooExport";

        author = config.DefaultAuthor;
        version = string.IsNullOrEmpty(config.DefaultVersion) ? "1.0" : config.DefaultVersion;

        if (string.IsNullOrEmpty(modName))
            modName = "SkinTattoo Decal";

        // Default-select all groups with layers
        selectedGroupIndices.Clear();
        for (int i = 0; i < project.Groups.Count; i++)
            if (project.Groups[i].Layers.Count > 0)
                selectedGroupIndices.Add(i);

        if (string.IsNullOrEmpty(description))
            description = $"Generated by SkinTattoo -- {selectedGroupIndices.Count} layer group(s)";

        IsOpen = true;
    }

    public override void Draw()
    {
        fileDialog.Draw();

        if (closeAfterExport)
        {
            closeAfterExport = false;
            IsOpen = false;
            return;
        }

        ImGui.Text(Strings.T("label.mod_name"));
        ImGui.SetNextItemWidth(-1);
        ImGui.InputText("##modName", ref modName, 128);

        ImGui.Text(Strings.T("label.author"));
        ImGui.SetNextItemWidth(-1);
        if (ImGui.InputText("##author", ref author, 64))
        {
            config.DefaultAuthor = author;
            config.Save();
        }

        ImGui.Text(Strings.T("label.version"));
        ImGui.SetNextItemWidth(120);
        if (ImGui.InputText("##version", ref version, 16))
        {
            config.DefaultVersion = version;
            config.Save();
        }

        ImGui.Text(Strings.T("label.description"));
        ImGui.SetNextItemWidth(-1);
        ImGui.InputTextMultiline("##desc", ref description, 1024, new Vector2(-1, 60));

        if (currentTarget == ExportTarget.LocalPmp)
        {
            ImGui.Text(Strings.T("label.export_path"));
            ImGui.SetNextItemWidth(-90);
            ImGui.InputText("##outPath", ref outputPath, 512);
            ImGui.SameLine();
            if (ImGui.Button(Strings.T("button.browse_output")))
            {
                var startDir = !string.IsNullOrEmpty(config.LastExportDir) && Directory.Exists(config.LastExportDir)
                    ? config.LastExportDir
                    : Environment.GetFolderPath(Environment.SpecialFolder.Desktop);
                var defaultName = SafeFileName(modName) + ".pmp";
                fileDialog.SaveFileDialog(Strings.T("dialog.save_mod"), ".pmp", defaultName, ".pmp", (ok, path) =>
                {
                    if (ok && !string.IsNullOrEmpty(path))
                    {
                        outputPath = path;
                        config.LastExportDir = Path.GetDirectoryName(path);
                        config.Save();
                    }
                }, startDir);
            }
        }

        ImGui.Separator();
        ImGui.Text(Strings.T("label.included_groups"));
        if (project.Groups.Count == 0)
        {
            ImGui.TextColored(new Vector4(1, 0.6f, 0, 1), Strings.T("hint.no_layer_groups"));
        }
        else
        {
            using (ImRaii.Child("##groups", new Vector2(-1, 120), true))
            {
                for (int i = 0; i < project.Groups.Count; i++)
                {
                    var g = project.Groups[i];
                    bool sel = selectedGroupIndices.Contains(i);
                    var label = Strings.T("hint.layer_group_fmt", g.Name, g.Layers.Count) + $"##g{i}";
                    if (ImGui.Checkbox(label, ref sel))
                    {
                        if (sel) selectedGroupIndices.Add(i);
                        else selectedGroupIndices.Remove(i);
                    }
                }
            }
        }

        ImGui.Separator();

        var canExport = !exporting && !string.IsNullOrWhiteSpace(modName) && selectedGroupIndices.Count > 0
            && (currentTarget != ExportTarget.LocalPmp || !string.IsNullOrWhiteSpace(outputPath));

        using (ImRaii.Disabled(!canExport))
        {
            var btnLabel = currentTarget == ExportTarget.LocalPmp ? Strings.T("button.export_local") : Strings.T("button.export_penumbra");
            if (exporting) btnLabel = Strings.T("button.exporting");
            if (ImGui.Button(btnLabel, new Vector2(160, 0)))
            {
                StartExport();
            }
        }
        ImGui.SameLine();
        if (ImGui.Button(Strings.T("button.close")))
            IsOpen = false;
    }

    private void StartExport()
    {
        if (exporting) return;

        var options = new ModExportOptions
        {
            ModName = modName.Trim(),
            Author = author.Trim(),
            Version = version.Trim(),
            Description = description,
            Target = currentTarget,
            OutputPmpPath = currentTarget == ExportTarget.LocalPmp ? outputPath : null,
        };
        foreach (var i in selectedGroupIndices)
            if (i >= 0 && i < project.Groups.Count)
                options.SelectedGroups.Add(project.Groups[i]);

        exporting = true;
        Task.Run(() =>
        {
            try
            {
                var result = exportService.Export(options);
                if (result.Success)
                    closeAfterExport = true;
            }
            finally { exporting = false; }
        });
    }

    private volatile bool closeAfterExport;

    private static string SafeFileName(string s)
    {
        var invalid = Path.GetInvalidFileNameChars();
        var chars = s.ToCharArray();
        for (int i = 0; i < chars.Length; i++)
            if (Array.IndexOf(invalid, chars[i]) >= 0) chars[i] = '_';
        var result = new string(chars).Trim();
        return string.IsNullOrEmpty(result) ? "SkinTattoo" : result;
    }
}
