name: Build

on:
  push:
    branches-ignore:
      - main
      - master
      - repo
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Prepare Environment
        uses: ./.github/actions/prepare-environment

      - name: Build
        uses: ./.github/actions/build-skintattoo
        with:
          configuration: Release
